# Setup
title:        Genomics of Biodiversity @ IBS 2019
tagline:       
baseurl:      
url:          https://rdtarvin.github.io/IBS2019_Genomics-of-Biodiversity/
paginate:     1
theme: jekyll-theme-cayman
future: true

# About/contact
author:
 name:       Becca Tarvin
 url:        http://www.tarvinlab.org

# Gems
plugins:
  - jekyll-paginate
  
# Google services
google_analytics: 

#Others
site:
 

